services:
    nextjs:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: website
        restart: always
        ports:
            - '3000:3000'
        volumes:
            - ./:/app
        environment:
            - NODE_ENV=development
            - WATCHPACK_POLLING=true
