services:
    strapi:
        build:
            context: .
            dockerfile: Dockerfile.strapi
        container_name: strapi
        restart: always
        ports:
            - '1337:1337'
        volumes:
            - ./cms-strapi:/srv/app
        environment:
            - HOST=0.0.0.0
            - PORT=1337
            - APP_KEYS=9Ab2WrZbBD36J9hpkJwsOA==,z3/94SrYD+Um/hY2XdlHoA==,CGO/3j34I5KObm8PcsyxCQ==,araMwsIAx+CQTjnjni/A5g==
            - API_TOKEN_SALT=Md+HNvsHVM/LLlc20W/duA==
            - ADMIN_JWT_SECRET=FIXpMf+OtYqVVWxLW0pLIA==
            - TRANSFER_TOKEN_SALT=veRfLGsmaq3p3pjd4bncEQ==
            - DATABASE_CLIENT=sqlite
            - DATABASE_FILENAME=/database/data.db
            - JWT_SECRET=0aeEVVhGx0d0FsU7ppV8Mw==
        healthcheck:
            test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://strapi:1337/admin']
            interval: 30s
            timeout: 10s
            retries: 3

    nextjs:
        build:
            context: .
            dockerfile: Dockerfile.nextjs
        container_name: website
        restart: always
        ports:
            - '3000:3000'
        volumes:
            - ./:/app
        environment:
            - NODE_ENV=development
            - WATCHPACK_POLLING=true
            - NEXT_PUBLIC_DEFAULT_LOCALE=nl
            - NEXT_PUBLIC_STRAPI_CLIENT_URL=http://localhost:1337
            - NEXT_PUBLIC_STRAPI_SERVER_URL=http://strapi:1337
        depends_on:
            - strapi
