services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: website
        restart: always
        ports:
            - '3000:3000'
        volumes:
            - ./:/app
            - /app/node_modules
            - /app/.next
        environment:
            - NODE_ENV=development
            - WATCHPACK_POLLING=true
